### ISSUE TITLE
up-grade-0.0.1 does not compile

### ISSUE THREAD

**Issue by peti** [ppenzin/up#1]
According to http://hydra.cryp.to/build/537624/log/raw, the module `Pkg` is missing from the release tarball.

**Comment by ppenzin** [comment]
Thank you fro the report. It indeed is missing: http://hackage.haskell.org/package/up-grade-0.0.1/src/src/

Will fix asap.

**Comment by ppenzin** [comment]
Uploaded a new version, deprecated the old one. Does it work now?

**Comment by ppenzin** [comment]
Package installs via cabal. Closing.
